apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-bff
  template:
    metadata:
      labels:
        app: nginx-bff
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config